#--SAVE SERVER--
#Leave these blank if you don't need this feature
Repository URL: ''
GitHub username: ''
#DO NOT share this with anyone!! I am NOT responsible for any account compromises.
GitHub password: ''